### ISSUE TITLE
Get setup with Discord Bots

### ISSUE THREAD

**Issue by grantmwilson** [engfrosh/engfrosh#10]
Follow along the documentation for [Discord.py](https://discordpy.readthedocs.io/en/stable/) on how to create a discord bot. Create your own discord bot that replies to peoples messages. 

Then try running the current `engfrosh_bot` and make sure it runs for you. Ask for help if it doesn't.

**Comment by mechanamoo** [comment]
https://www.youtube.com/playlist?list=PLW3GfRiBCHOhfVoiDZpSz8SM_HybXRPzZ
