### ISSUE TITLE
Write simple music bot for discord

### ISSUE THREAD

**Issue by grantmwilson** [engfrosh/engfrosh#15]
We will be getting spotify premium, etc, so we would like to be able to use our own music bot. Look into it and add basic functionality of connecting, playing a certain song, and disconnecting.

**Comment by intelligent-box** [comment]
possible source https://github.com/Just-Some-Bots/MusicBot

**Comment by intelligent-box** [comment]
> possible source https://github.com/Just-Some-Bots/MusicBot

this allows us to use Spotify premium accounts for each bot too, with Spotify API integrated already. all we need to do is configure and start each bot, or run them in a docker configuration. One for each team and a master bot for spirit to control
