### ISSUE TITLE
Research options for streaming a movie to many frosh (>50)

### ISSUE THREAD

**Issue by grantmwilson** [engfrosh/engfrosh#24]
Coffeehouse will be streaming a movie to many frosh as an activity one night. We need to find an option that will let them stream a movie to all frosh that want to watch, and the cap of 50 on Discord is too low. Look into and present some other options. It doesn't have to be free as we can allocate a _small_ amount of budget if needed.

**Comment by pruthvichivukula** [comment]
Have we given any thought to just using zoom? Idk if it breaks their TOS but given that lectures over zoom are generally pretty accessible, it may work.

The ability to mute everyone exists, and I think separate chats can be created for teams. Additionally, if users are on computers, they can also join a discord voice channel and talk over the movie with their teams.

**Comment by grantmwilson** [comment]
That's a really good point / idea. I'm going to look more into that because that does sound like the easiest.
