### ISSUE TITLE
Increase security with tickets

### ISSUE THREAD

**Issue by grantmwilson** [engfrosh/engfrosh#99]
Ideally there would be permissions attached to the tickets so only the person who opened it and the staff with appropriate permissions to view that type of ticket can see it.

At a minimum I would also like to see non sequential ticket ids.

**Comment by finlaywashere** [comment]
Currently only the person who opened the ticket and staff can view it per `can_view_ticket` in `engfrosh_site/ticket/views.py`

**Comment by finlaywashere** [comment]
This should also make the sequential ids a non issue as only the opener can access them
